version: "3.7"
services:
  app:
    build:
      args:
        user: sammy
        uid: 1000
      context: ./backend/
      dockerfile: Dockerfile
    image: cargo
    container_name: cargo-app
    restart: unless-stopped
    tty: true
    working_dir: /var/www/
    volumes:
      - ./backend/:/var/www
    networks:
      - cargo

  db:
    image: mysql:8.0
    container_name: cargo-db
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    ports:
      - 3306:3306
    volumes:
      - ./.docker/mysql:/docker-entrypoint-initdb.d
    networks:
      - cargo

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8888:80
    links:
      - db:db
    environment:
      MYSQL_USERNAME: ${DB_USERNAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      PMA_HOST: ${DB_HOST}
      PMA_PORT: ${DB_PORT}
    networks:
      - cargo

  nginx:
    image: nginx:1.17-alpine
    container_name: cargo-nginx
    restart: unless-stopped
    tty: true
    ports:
      - 7777:80
      - 7773:443
    volumes:
      - ./backend/:/var/www
      - ./.docker/nginx:/etc/nginx/conf.d
    networks:
      - cargo

networks:
  cargo:
    driver: bridge
